version: 2
jobs:
  build-one:
    macos:
      xcode: 11.3.0
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: xcodebuild -11.3.0
      - run: echo "HI FRIEND!!"
  build-two:
    macos:
      xcode: 11.3.0
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: xcodebuild -11.3.0
      - run: echo "HELLO AGAIN!!"
workflows:
  version: 2
  build-both:
    - build-one
    - build-two
