version: 2
jobs:
  build:
    docker:
    - image: circleci/node:8.9
    steps:
    - checkout
    - run:
        command: echo "npm installing"
    - run:
        command: npm install
    - run:
        command: CI= true npm run build
  hithere:
    docker:
    - image: circleci/node:8.9
    steps:
    - checkout
    - run:
        command: echo "hellllooooo!"
  test:
    docker:
    - image: circleci/node:8.9
    steps:
    - checkout
    - run:
        command: echo "testing stuff"
    - run:
        command: npm install
    - run:
        command: npm test
workflows:
  version: 2
  build_test_and_lint:
    jobs:
    - build
    - hithere
    - test:
        requires:
        - hithere
