version: 2
jobs:
  build_one:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - run: echo "Why....Hello there!"
  build_two:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - run: echo "Why....not?!"
  workflows:
    version: 2
    build_onetwo:
      jobs:
        - build_one
        - build_two
